### ISSUE TITLE
[Bug]: no action menu on the rating cards in the user profile page

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#103]
### URL of the Page

https://postreview-app.herokuapp.com/profile

### What happened?

There is currently no way to edit, remove or make ratings anonymous from the user profile page.
![image](https://user-images.githubusercontent.com/73071333/153630087-58fe7321-a022-425b-b3e2-e3818dc77b6a.png)
Wireframe for reference: https://whimsical.com/user-page-KN8xxZWDHtrZNdYqAbyc93@2Ux7TurymNLPL8ruw2vL
It's not a huge problem if users can do it elsewhere. I think you can edit your rating from the paper page. Is the only way to make a rating anonymous - to resubmit the same rating but turn on the anonymous tumbler as you submit it? We probably need a better way. And it doesn't look like there is a way to delete the rating at the moment, is that correct (we probably need this one for the MVP)?

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
@coglebed I worked on this a bit. Along the way, I thought that having a "Make Anonymous" button may not make sense, since the popup for editing a review will have a make anonymous toggle button. Instead, having only two options (Edit and Delete) may work. What do you think?

Since there are only two options, icons may work better.

Either something like this:

![image](https://user-images.githubusercontent.com/17035406/154965007-5366cac0-0f89-481d-99e5-59f7adef4bc8.png)


Or the version where the "delete" icon is colorless (red may be too strong?):

![image](https://user-images.githubusercontent.com/17035406/154965579-bd1d2574-15c6-4ba3-8f02-990e5345feb9.png)

**Comment by nsunami** [comment]
We talked synchronously and decided that we go with the initial design for now 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/17035406/154997110-52e71d2a-1a68-4cfb-81b9-59c383508cb3.png">

We can think about improvements later.

**Comment by nsunami** [comment]
@all-contributors please add @coglebed for bug reports
(I thought I already did this before but it's not showing up on README---doing it again!)
