### ISSUE TITLE
[Bug]: there is a "rate a paper" empty state in the user profile page

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#75]
### URL of the Page

https://postreview-app.herokuapp.com/profile#

### What happened?

there is a "rate a paper" empty state in the user profile page - there shouldn't be one there I think (where would it lead?) - it should only be on the paper page, not user profile
![image](https://user-images.githubusercontent.com/73071333/150153256-024b733f-b640-413d-909f-036acfe42c63.png)

### Steps to reproduce

1. get to the user page 
2. look :) 
3. it's also unclickable 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
Ok! I was following the Whimsical mockup below. But, I agree that having a rate a paper empty state would potentially be confusing. 

![image](https://user-images.githubusercontent.com/17035406/151166784-25339037-a48e-4c8d-ace6-8739ba83a98f.png)

We can potentially address this issue in two ways:

1. We just remove the empty state. The space will just say "No ratings submitted yet"
2. We build another submission routine (maybe a pop-up) so that users clicking the empty state can enter a DOI and add paper.

I think `#1` is a way to go, as you implied. Just wanted to check with you if that's the case.

**Comment by coglebed** [comment]
Okay, sorry for contradicting mockup and comments heh
Yeah, option #1 is probably a way to go for now.

**Comment by nsunami** [comment]
Thanks! Will remove the empty state then
