### ISSUE TITLE
[Bug]: Change colors of the rating stars

### ISSUE THREAD

**Issue by coglebed** [nsunami/postreview-app#79]
### URL of the Page

https://postreview-app.herokuapp.com/

### What happened?

There is only one star currently. Multiple starts will need to be added for MVP, overall star and individual stars need to be of different color and star size need to be dependent on the average score.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nsunami** [comment]
@coglebed I think this issue was submitted when we were seeing papers without reviews.
Currently, we have stars presented something like below:
![image](https://user-images.githubusercontent.com/17035406/151165923-cf3362e4-979d-42d1-8c0b-5e2c3aff2132.png)

(That said, the numbers are not showing on top of the stars for now--can be another issue)

**Comment by coglebed** [comment]
I like it, can we play with the colors?
#FF5733 for Total and #FFC300 for Subratings
